# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, it might be a sign that you should
# consider using Jekyll's data files or other features instead.

title: Derby City Recovery
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Recovery is an Action
  Join a community, start a community, and discover a new you.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://derbycityrecovery.space" # the base hostname and protocol for your site, e.g. https://example.com
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

